### ISSUE TITLE
Failing to create new grok pattern in Graylog

### ISSUE THREAD

**Issue by madchap** [madchap/graylog2-selinux#1]
Version 2.1

2016-11-15T23:41:32.432Z WARN  [GrokPatternServiceImpl] Invalid regular expression syntax for 'SELINUX_AVC' with pattern type=%{WORD:sel_type} msg=%{WORD:sel_msg_type}\(%{GREEDYDATA:sel_audit_ref}\): avc: %{WORD:sel_access_decision} { %{WORD:sel_target_function} }(?: for pid=%{BASE10NUM:sel_pid})(?: comm="%{NOTSPACE:sel_comm}")?(?: capability=%{GREEDYDATA:sel_capability})?(?: path="%{NOTSPACE:sel_path}")?(?: name="%{NOTSPACE:sel_path_name}")?(?: dev=%{NOTSPACE:sel_dev} ino=%{BASE10NUM:sel_ino})?(?: laddr=%{NOTSPACE:sel_laddr})?(?: lport=%{NOTSPACE:sel_lport})?(?: faddr=%{NOTSPACE:sel_faddr})?(?: fport=%{NOTSPACE:sel_fport})?(?: path=%{NOTSPACE:sel_filesocket_path})?(?: saddr=%{NOTSPACE:sel_saddr})?(?: src:%{NOTSPACE:sel_src})?(?: daddr=%{NOTSPACE}:sel_daddr)?(?: dest=%{NOTSPACE:%{sel_dest}})?(?: netif=%{NOTSPACE:sel_netif})?(?: sauid=%{NOTSPACE:sel_sauid})?(?: hostname=%{NOTSPACE:sel_hostname})?(?: addr=%{NOTSPACE:sel_addr})?(?: terminal=%{NOTSPACE:sel_terminal})?(?: resid=%{NOTSPACE:sel_resid})?(?: restype=%{NOTSPACE:sel_restype})? scontext=%{NOTSPACE:sel_scontext} tcontext=%{NOTSPACE:sel_tcontext} tclass=%{NOTSPACE:sel_tclass}

java.util.regex.PatternSyntaxException: Illegal repetition near index 46
(type=(null) msg=(null)\((null)\): avc: (null) { (null) }(?: for pid=(null))(?: comm="(null)")?(?: capability=(null))?(?: path="(null)")?(?: name="(null)")?(?: dev=(null) ino=(null))?(?: laddr=(null))?(?: lport=(null))?(?: faddr=(null))?(?: fport=(null))?(?: path=(null))?(?: saddr=(null))?(?: src:(null))?(?: daddr=(null):sel_daddr)?(?: dest=%{NOTSPACE:(null)})?(?: netif=(null))?(?: sauid=(null))?(?: hostname=(null))?(?: addr=(null))?(?: terminal=(null))?(?: resid=(null))?(?: restype=(null))? scontext=(null) tcontext=(null) tclass=(null))
                                              ^
        at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_102]
        at java.util.regex.Pattern.closure(Pattern.java:3157) ~[?:1.8.0_102]
        at java.util.regex.Pattern.sequence(Pattern.java:2134) ~[?:1.8.0_102]
        at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_102]
        at java.util.regex.Pattern.group0(Pattern.java:2905) ~[?:1.8.0_102]
        at java.util.regex.Pattern.sequence(Pattern.java:2051) ~[?:1.8.0_102]
        at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_102]
        at java.util.regex.Pattern.compile(Pattern.java:1696) ~[?:1.8.0_102]
        at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_102]
        at java.util.regex.Pattern.compile(Pattern.java:1054) ~[?:1.8.0_102]
        at com.google.code.regexp.Pattern.buildStandardPattern(Unknown Source) ~[graylog.jar:?]
        at com.google.code.regexp.Pattern.<init>(Unknown Source) ~[graylog.jar:?]
        at com.google.code.regexp.Pattern.compile(Unknown Source) ~[graylog.jar:?]
        at oi.thekraken.grok.api.Grok.compile(Grok.java:391) ~[graylog.jar:?]
        at oi.thekraken.grok.api.Grok.compile(Grok.java:328) ~[graylog.jar:?]
        at org.graylog2.grok.GrokPatternServiceImpl.validate(GrokPatternServiceImpl.java:106) [graylog.jar:?]
        at org.graylog2.grok.GrokPatternServiceImpl.save(GrokPatternServiceImpl.java:78) [graylog.jar:?]
        at org.graylog2.rest.resources.system.GrokResource.createPattern(GrokResource.java:102) [graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

**Comment by madchap** [comment]
The curly braces had to be escaped for java, while it didn't matter to grokdebug.
